// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
        int Above = 0;
        int BelowOrEqual = 0;
        for (int i = 0; i < N; i++) {
            double randomValue = Math.random();

            if (randomValue > 0.5) {
                Above++;
            } else {
                BelowOrEqual++;
            }
        }
        System.out.println("> 0.5: " + Above + " times");
        System.out.println("<= 0.5: " + BelowOrEqual + " times");    
        if (BelowOrEqual != 0 && Above != 0) {
            double ratio = (double) Above / BelowOrEqual;
            System.out.println("Ratio: " + ratio);
        }
    }

}
